services:
  battleship.app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "7242:443"
    depends_on:
      - battleship.api
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/certs/app-certificate.crt:/etc/nginx/app-certificate.crt
      - ./config/certs/app-certificate.key:/etc/nginx/app-certificate.key
    environment:
      - ApiHost=https://localhost:7202
      - Auth0__Authority=https://dev-kmr8fp2o7chnzuyx.eu.auth0.com
      - Auth0__ClientId=hpD5pXOvFeSb11jcEQioaZTksqkF03FC
      - Auth0__Audience=https://localhost:7202

  battleship.api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "7202:443"
    environment:
    - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api-certificate.pfx
    - ASPNETCORE_URLS=https://+;http://+
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./config/certs/api-certificate.pfx:/https/api-certificate.pfx