name: Continuous Delivery

on:
  push:
    branches:
      - master    
  release:
    types: [published]

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.app -t ${{ secrets.DOCKER_USERNAME }}/battleship.app:${{ env.BRANCH_NAME }}-${{ github.sha }} .
          docker build -f Dockerfile.api -t ${{ secrets.DOCKER_USERNAME }}/battleship.api:${{ env.BRANCH_NAME }}-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.app:${{ env.BRANCH_NAME }}-${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.api:${{ env.BRANCH_NAME }}-${{ github.sha }}

  docker-publish-on-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check if Docker App image exists
        id: check_image_app
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/battleship.app:master-${{ github.sha }} || echo "Docker image not found"
      
      - name: Check if Docker Api image exists
        id: check_image_api
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/battleship.api:master-${{ github.sha }} || echo "Docker image not found"

      - name: Tag and push Docker image if exists
        if: steps.check_image_app.run != 'Docker image not found' && steps.check_image_api.run != 'Docker image not found'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/battleship.app:master-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/battleship.app:${{ github.event.release.tag_name }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/battleship.app:master-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/battleship.app:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/battleship.api:master-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/battleship.api:${{ github.event.release.tag_name }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/battleship.api:master-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/battleship.api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.app:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.api:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/battleship.api:latest
